workflows:
  android-flow:
    name: A demo workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      android_signing:
        - smarty-key
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/Library/Caches/CocoaPods
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
    - name: Echo envs
      script: |
        echo $HOME
        echo $CM_BUILD_DIR
    - name: Set up local.properties
      working_directory: example
      script: | 
        echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/example/android/local.properties"
    - name: Get Flutter packages
      working_directory: example
      script: | 
        flutter packages pub get
    - name: Build APK with Flutter
      working_directory: example
      script: | 
        flutter build apk --release
    artifacts:
      - build/**/outputs/apk/**/*.apk
    publishing:
      email:
        notify:
          success: true
          failure: false
        recipients:
          - abadasamuelosp@gmail.com
    