workflows:
  android-flow:
    name: A demo workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      android_signing:
        - smarty-key
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/Library/Caches/CocoaPods
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
        - pattern: master
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
    - name: 🐦 Install Shorebird
      script: |
        curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash -s -- --force
        install_path=$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.shorebird" || printf %s "${XDG_CONFIG_HOME}/shorebird")
        echo 'PATH="$install_path/bin:$PATH"' >> ~/.profile
        echo 'export PATH' >> ~/.profile
        source ~/.profile
        echo "added $install_path/bin to PATH"
      ignore_failure: true
    - name: Shorebird doctor
      script: |
        shorebird doctor
      ignore_failure: true
    - name: Set up local.properties
      working_directory: example
      script: | 
        echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/example/android/local.properties"
    - name: Get Flutter packages
      script: | 
        flutter packages pub get
    - name: Run Flutter lint and analysis
      script: | 
        flutter analyze .
      ignore_failure: true
    - name: Run Flutter tests
      script: | 
        flutter test
      ignore_failure: true
    - name: Build APK with Flutter
      working_directory: example
      script: | 
        flutter build apk --release
    artifacts:
      - example/build/**/outputs/**/*.apk
    publishing:
      email:
        notify:
          success: true
          failure: false
        recipients:
          - abadasamuelosp@gmail.com